### ISSUE TITLE
easier to read documentation

### ISSUE THREAD

**Issue by Josiah-tan** [user202729/plover-python-dictionary-lib#1]
This library so far has been the best thing that I have ever seen, I personally think that this has quite a lot of potential!
I've been using this library to create my own plugins (plover-vim)
but I found that I had to take a while to read through your example code to understand what was happening and all the use cases
it would be nice if there was some official documentation with easier examples so that more people can learn about this library more easily

Mostly I think it would be nice if these key ideas were mentioned in the readme:
- dictionary operations:
  -  *, / and | 
- named dictionaries
  - like using .named() to create custom behavior for joining the translations of dictionaries (if I understood it correctly)

(random side note: I think plover + telescope-nvim has a lot of potential)

**Comment by user202729** [comment]
Maybe I should just rename this file to add 00_ at the top. I did leave comment for this one.

https://github.com/user202729/plover-python-dictionary-lib/blob/7e3d9755d2b603cc284977cc218f68a04b65fc52/example/two_letter_fingerspelling_example.py#L82-L85

Other than that, people can make pull requests.

**Comment by Josiah-tan** [comment]
00 sounds good to me I might make a pull request later
